server:
  port: 8082

spring:
  application:
    name: one-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

graphite:
  metric:
    prefix: one-service
  host: localhost
  port: 2003

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

api-gateway-service:
  ribbon:
    listOfServers: localhost:8765