server:
  port: 8084

spring:
  application:
    name: two-api-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

api-gateway-service:
  ribbon:
    listOfServers: localhost:8765